### ISSUE TITLE
[Bug] Cannot find matching keyid

### ISSUE THREAD

**Issue by JohnDotOwl** [devflowinc/firecrawl-simple#33]
Command 
docker compose up

Error from API Service
```
api-1                | /usr/local/lib/node_modules/corepack/dist/lib/corepack.cjs:21535                                                                       
api-1                |   if (key == null || signature == null) throw new Error(`Cannot find matching keyid: ${JSON.stringify({ signatures, keys })}`);
api-1                |                                               ^                                                                                        
api-1                |                                                                                                                                        
api-1                | Error: Cannot find matching keyid: {"signatures":[{"sig":"MEUCIQDyfmLzYs4+Vuw7JzxVlrTiIwJRZkzt35fLezmouCyTvQIgHpODPYfD80JbZokwC+LKxJoaGoYkgcFhB4gqt7j0anA=","keyid":"SHA256:DhQ8wR5APBvFHLF/+Tc+AYvPOdTpcIDqOhxsBHRwC7U"}],"keys":[{"expires":null,"keyid":"SHA256:jl3bwswu80PjjokCgh0o2w5c2U4LhQAE57gj9cz1kzA","keytype":"ecdsa-sha2-nistp256","scheme":"ecdsa-sha2-nistp256","key":"MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE1Olb3zMAFFxXKHiIkQO5cJ3Yhl5i6UPp+IhuteBJbuHcA5UogKo0EWtlWwW6KSaKoTNEYL7JlCQiVnkhBktUgg=="}]}
api-1                |     at verifySignature (/usr/local/lib/node_modules/corepack/dist/lib/corepack.cjs:21535:47)
api-1                |     at fetchLatestStableVersion (/usr/local/lib/node_modules/corepack/dist/lib/corepack.cjs:21553:5)                                   
api-1                |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)                                                      
api-1                |     at async fetchLatestStableVersion2 (/usr/local/lib/node_modules/corepack/dist/lib/corepack.cjs:21672:14)                           
api-1                |     at async Engine.getDefaultVersion (/usr/local/lib/node_modules/corepack/dist/lib/corepack.cjs:22292:23)                            
api-1                |     at async Engine.executePackageManagerRequest (/usr/local/lib/node_modules/corepack/dist/lib/corepack.cjs:22390:47)                 
api-1                |     at async Object.runMain (/usr/local/lib/node_modules/corepack/dist/lib/corepack.cjs:23096:5)                                       
api-1                |                                                                                                                                        
api-1                | Node.js v20.17.0
api-1 exited with code 1 
```

.env file
```
# ===== Required ENVS ======
PORT=3002
HOST=0.0.0.0

# To turn on DB authentication, you need to set up Supabase.
USE_DB_AUTHENTICATION=false

# ===== Optional ENVS ======

## === AI features (JSON format on scrape, /extract API) ===
# Provide your OpenAI API key here to enable AI features
# OPENAI_API_KEY=

# Experimental: Use Ollama
# OLLAMA_BASE_URL=http://localhost:11434/api
# MODEL_NAME=deepseek-r1:7b
# MODEL_EMBEDDING_NAME=nomic-embed-text

# Experimental: Use any OpenAI-compatible API
# OPENAI_BASE_URL=https://example.com/v1
# OPENAI_API_KEY=

## === Proxy ===
# PROXY_SERVER can be a full URL (e.g. http://0.1.2.3:1234) or just an IP and port combo (e.g. 0.1.2.3:1234)
# Do not uncomment PROXY_USERNAME and PROXY_PASSWORD if your proxy is unauthenticated
# PROXY_SERVER=
# PROXY_USERNAME=
# PROXY_PASSWORD=

## === /search API ===
# By default, the /search API will use Google search.

# You can specify a SearXNG server with the JSON format enabled, if you'd like to use that instead of direct Google.
# You can also customize the engines and categories parameters, but the defaults should also work just fine.
# SEARXNG_ENDPOINT=http://your.searxng.server
# SEARXNG_ENGINES=
# SEARXNG_CATEGORIES=

## === Other ===

# Supabase Setup (used to support DB authentication, advanced logging, etc.)
# SUPABASE_ANON_TOKEN=
# SUPABASE_URL=
# SUPABASE_SERVICE_TOKEN=

# Use if you've set up authentication and want to test with a real API key
# TEST_API_KEY=

# You can add this to enable ScrapingBee as a fallback scraping engine.
# SCRAPING_BEE_API_KEY=

# This key lets you access the queue admin panel. Change this if your deployment is publicly accessible.
BULL_AUTH_KEY=xxx

# This is now autoconfigured by the docker-compose.yaml. You shouldn't need to set it.
# PLAYWRIGHT_MICROSERVICE_URL=http://playwright-service:3000/scrape
# REDIS_URL=redis://redis:6379
# REDIS_RATE_LIMIT_URL=redis://redis:6379

# Set if you have a llamaparse key you'd like to use to parse pdfs
# LLAMAPARSE_API_KEY=

# Set if you'd like to send server health status messages to Slack
# SLACK_WEBHOOK_URL=

# Set if you'd like to send posthog events like job logs
# POSTHOG_API_KEY=
# POSTHOG_HOST=

# === Performance Settings ===
# Number of worker processes per queue (controls how many jobs can be processed simultaneously)
NUM_WORKERS_PER_QUEUE=6

# Maximum number of concurrent browser sessions in the playwright service
MAX_CONCURRENCY=10

# Whether to block media requests like images and videos to improve performance
BLOCK_MEDIA=true

# Level of detail in logging (debug, info, warn, error)
LOGGING_LEVEL=info

# Resource limits (as decimal percentage, e.g. 0.8 = 80%)
MAX_RAM=0.9
MAX_CPU=0.9

# Optional: For solving captchas (if needed)
# TWOCAPTCHA_TOKEN=

# Redis URL can be customized if needed
# FIRECRAWL_REDIS_URL=redis://redis:6379
```

**Comment by JohnDotOwl** [comment]
Solution : .env


```
name: firecrawl

x-common-service: &common-service
  build: apps/api
  networks:
    - backend
  environment:
    - REDIS_URL=${REDIS_URL:-redis://redis:6379}
    - REDIS_RATE_LIMIT_URL=${REDIS_URL:-redis://redis:6379}
    - PLAYWRIGHT_MICROSERVICE_URL=${PLAYWRIGHT_MICROSERVICE_URL:-http://playwright-service:3000}
    - PORT=${PORT:-3002}
    - NUM_WORKERS_PER_QUEUE=${NUM_WORKERS_PER_QUEUE}
    - BULL_AUTH_KEY=${BULL_AUTH_KEY}
    - TEST_API_KEY=${TEST_API_KEY}
    - HOST=${HOST:-0.0.0.0}
    - LOGGING_LEVEL=${LOGGING_LEVEL}
    - MAX_RAM=${MAX_RAM:-0.95}
    - MAX_CPU=${MAX_CPU:-0.95}
  extra_hosts:
    - "host.docker.internal:host-gateway"

services:
  puppeteer-service:
    image: trieve/puppeteer-service-ts
    build:
      context: ./apps/puppeteer-service-ts/
      dockerfile: Dockerfile
    environment:
      - PORT=3000
      - PROXY_SERVER=${PROXY_SERVER}
      - PROXY_USERNAME=${PROXY_USERNAME}
      - PROXY_PASSWORD=${PROXY_PASSWORD}
      - TWOCAPTCHA_TOKEN=${TWOCAPTCHA_TOKEN}
      - MAX_CONCURRENCY=${MAX_CONCURRENCY}
    networks:
      - backend

  api:
    image: trieve/firecrawl
    <<: *common-service
    depends_on:
      - redis
      - puppeteer-service
    ports:
      - "3002:3002"
    command: ["pnpm", "run", "start:production"]

  worker:
    <<: *common-service
    depends_on:
      - redis
      - puppeteer-service
      - api
    command: ["pnpm", "run", "workers"]

  redis:
    image: redis:alpine
    networks:
      - backend
    command: redis-server --bind 0.0.0.0

networks:
  backend:
    driver: bridge

```
